{
 "title": "Demo 9800L",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "Collector", "query": "buckets()" },
   {
    "name": "WLC",
    "label": "WLC",
    "query": "from(bucket: \"${Collector}\")\n  |> range(start: v.timeRangeStart, stop: now())\n  |> keyValues(keyColumns: [\"source\"])\n  |> group(columns: [\"source\"])\n  |> keep(columns: [\"source\"])\n  |> distinct(column: \"source\")"
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime $WLC",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${Collector}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XE-device-hardware-oper:device-hardware-data/device-hardware\")\n  |> filter(fn: (r) => r[\"source\"] == \"${WLC}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"device_system_data/boot_time\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> drop(columns: [\"_time\", \"_start\", \"_stop\"]) // drop timestamp columns\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "S/N $WLC",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${Collector}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XE-device-hardware-oper:device-hardware-data/device-hardware\")\n  |> filter(fn: (r) => r[\"source\"] == \"${WLC}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"device_inventory/serial_number\")\n  |> drop(columns: [\"host\", \"path\", \"source\", \"subscription\"])\n\n\n"
    }
   ]
  },
  {
   "title": "Version $WLC",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${Collector}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XE-native:native\")\n  |> filter(fn: (r) => r[\"_field\"] == \"version\")\n  |> drop(columns: [\"host\", \"path\", \"source\", \"subscription\"])\n\n\n"
    }
   ]
  },
  {
   "title": "Last reload reason $WLC",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${Collector}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XE-device-hardware-oper:device-hardware-data/device-hardware\")\n  |> filter(fn: (r) => r[\"source\"] == \"${WLC}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"device_system_data/last_reboot_reason\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> drop(columns: [\"_time\", \"_start\", \"_stop\"]) // drop timestamp columns\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 6, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${Collector}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XE-process-cpu-oper:cpu-usage/cpu-utilization\")\n  |> filter(fn: (r) => r[\"source\"] == \"${WLC}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"five_seconds\" or r[\"_field\"] == \"one_minute\" or r[\"_field\"] == \"five_minutes\") \n  |> drop(columns: [\"host\", \"path\", \"source\", \"subscription\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n"
    }
   ]
  },
  {
   "title": "$WLC Temperature",
   "type": "bargauge",
   "description": "|  Sensor         | Threshold (Minor,Major,Critical,Shutdown) |\n| --------------- | ----------------------------------------- |\n|  Temp: BRDTEMP1 |     (54 ,57 ,60 ,61 )(Celsius)            |\n|  Temp: BRDTEMP2 |     (58 ,61 ,64 ,65 )(Celsius)            |\n|  Temp: CPU Die  |     (94 ,99 ,104,105)(Celsius)            |",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${Collector}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XE-environment-oper:environment-sensors/environment-sensor\")\n  |> filter(fn: (r) => r[\"_field\"] == \"current_reading\")\n  |> drop(columns: [\"host\", \"path\", \"source\", \"subscription\", \"location\",])\n"
    }
   ]
  },
  {
   "title": "Memory used $WLC",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "from(bucket: \"${Collector}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XE-memory-oper:memory-statistics/memory-statistic\")\n  |> filter(fn: (r) => r[\"_field\"] == \"used_memory\")\n  |> filter(fn: (r) => r[\"source\"] == \"${WLC}\")\n  |> filter(fn: (r) => r[\"name\"] == \"Processor\")\n  |> drop(columns: [\"host\", \"path\", \"source\", \"subscription\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n"
    }
   ]
  },
  {
   "title": "Memory free $WLC",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "from(bucket: \"${Collector}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XE-memory-oper:memory-statistics/memory-statistic\")\n  |> filter(fn: (r) => r[\"_field\"] == \"free_memory\")\n  |> filter(fn: (r) => r[\"source\"] == \"${WLC}\")\n  |> filter(fn: (r) => r[\"name\"] == \"Processor\")\n  |> drop(columns: [\"host\", \"path\", \"source\", \"subscription\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n"
    }
   ]
  },
  {
   "title": "Device Traffic $WLC",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "targets": [
    {
     "query": "from(bucket: \"${Collector}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XE-interfaces-oper:interfaces/interface\")\n  |> filter(fn: (r) => r[\"_field\"] == \"statistics/rx_kbps\" or r[\"_field\"] == \"statistics/tx_kbps\")\n  |> filter(fn: (r) => r[\"source\"] == \"${WLC}\")\n  |> filter(fn: (r) => r[\"_value\"] > 0)\n  |> drop(columns: [\"host\", \"path\", \"source\", \"subscription\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n"
    }
   ]
  },
  {
   "title": "Packet Counter $WLC",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"${Collector}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XE-interfaces-oper:interfaces/interface\")\n  |> filter(fn: (r) => r[\"_field\"] == \"statistics/rx_pps\" or r[\"_field\"] == \"statistics/tx_pps\")\n  |> filter(fn: (r) => r[\"source\"] == \"${WLC}\")\n  |> filter(fn: (r) => r[\"_value\"] > 0)\n  |> drop(columns: [\"host\", \"path\", \"source\", \"subscription\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n"
    }
   ]
  },
  {
   "title": "BRDTEMP1",
   "type": "gauge",
   "description": " Threshold(Minor,Major,Critical,Shutdown)\n ---------------------------------------\n     (54 ,57 ,60 ,61 )(Celsius)",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${Collector}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XE-environment-oper:environment-sensors/environment-sensor\")\n  |> filter(fn: (r) => r[\"source\"] == \"${WLC}\")\n  |> filter(fn: (r) => r[\"name\"] == \"Temp: BRDTEMP1\")\n  |> filter(fn: (r) => r[\"_field\"] == \"current_reading\")"
    }
   ]
  },
  {
   "title": "BRDTEMP2",
   "type": "gauge",
   "description": " Threshold(Minor,Major,Critical,Shutdown)\n ---------------------------------------\n     (54 ,57 ,60 ,61 )(Celsius)",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${Collector}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XE-environment-oper:environment-sensors/environment-sensor\")\n  |> filter(fn: (r) => r[\"source\"] == \"${WLC}\")\n  |> filter(fn: (r) => r[\"name\"] == \"Temp: BRDTEMP2\")\n  |> filter(fn: (r) => r[\"_field\"] == \"current_reading\")"
    }
   ]
  },
  {
   "title": "CPU Die",
   "type": "gauge",
   "description": " Threshold(Minor,Major,Critical,Shutdown)\n ---------------------------------------\n     (54 ,57 ,60 ,61 )(Celsius)",
   "gridPos": { "h": 8, "w": 3, "x": 6, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${Collector}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XE-environment-oper:environment-sensors/environment-sensor\")\n  |> filter(fn: (r) => r[\"source\"] == \"${WLC}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"current_reading\")\n  |> filter(fn: (r) => r[\"name\"] == \"Temp: CPU Die\")\n\n"
    }
   ]
  },
  {
   "title": "PID",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 9, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${Collector}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XE-device-hardware-oper:device-hardware-data/device-hardware\")\n  |> filter(fn: (r) => r[\"_field\"] == \"device_inventory/part_number\")\n  |> filter(fn: (r) => r[\"source\"] == \"${WLC}\")\n"
    }
   ]
  }
 ]
}