{
 "title": "Demo 9840",
 "tags": [
  "Demo",
  "Wireless"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "Collector", "query": "buckets()" },
   {
    "name": "WLC",
    "label": "WLC",
    "query": "from(bucket: \"${Collector}\")\n  |> range(start: v.timeRangeStart, stop: now())\n  |> keyValues(keyColumns: [\"source\"])\n  |> group(columns: [\"source\"])\n  |> keep(columns: [\"source\"])\n  |> distinct(column: \"source\")"
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime $WLC",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${Collector}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XE-device-hardware-oper:device-hardware-data/device-hardware\")\n  |> filter(fn: (r) => r[\"source\"] == \"${WLC}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"device_system_data/boot_time\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> drop(columns: [\"_time\", \"_start\", \"_stop\"]) // drop timestamp columns\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Version $WLC",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${Collector}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XE-native:native\")\n  |> filter(fn: (r) => r[\"_field\"] == \"version\")\n  |> drop(columns: [\"host\", \"path\", \"source\", \"subscription\"])\n\n\n"
    }
   ]
  },
  {
   "title": "ROMMON $WLC",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${Collector}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XE-device-hardware-oper:device-hardware-data/device-hardware\")\n  |> filter(fn: (r) => r[\"_field\"] == \"device_system_data/rommon_version\")\n  |> filter(fn: (r) => r[\"source\"] == \"${WLC}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> map(fn: (r) => ({ value: r[\"_value\"] }))\n  |> yield(name: \"last\")\n"
    }
   ]
  },
  {
   "title": "Last reload reason $WLC",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${Collector}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XE-device-hardware-oper:device-hardware-data/device-hardware\")\n  |> filter(fn: (r) => r[\"source\"] == \"${WLC}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"device_system_data/last_reboot_reason\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> drop(columns: [\"_time\", \"_start\", \"_stop\"]) // drop timestamp columns\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 7, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${Collector}\")\n  |> range(start: -15m)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XE-process-cpu-oper:cpu-usage/cpu-utilization\")\n  |> filter(fn: (r) => r[\"source\"] == \"${WLC}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"five_seconds\" or r[\"_field\"] == \"one_minute\" or r[\"_field\"] == \"five_minutes\") \n  |> drop(columns: [\"host\", \"path\", \"source\", \"subscription\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"${Collector}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XE-process-cpu-oper:cpu-usage/cpu-utilization\")\n  |> filter(fn: (r) => r[\"source\"] == \"${WLC}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"five_seconds\" or r[\"_field\"] == \"one_minute\" or r[\"_field\"] == \"five_minutes\") \n  |> drop(columns: [\"host\", \"path\", \"source\", \"subscription\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n"
    }
   ]
  },
  {
   "title": "$WLC Temp: RCRX IN",
   "type": "bargauge",
   "description": "|  Sensor         | Threshold (Minor,Major,Critical,Shutdown) |\n| --------------- | ----------------------------------------- |\n|  RCRX IN  |     (52 ,57 ,62 ,73 )(Celsius)            |",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${Collector}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XE-environment-oper:environment-sensors/environment-sensor\")\n  |> filter(fn: (r) => r[\"source\"] == \"${WLC}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"current_reading\")\n  |> filter(fn: (r) => r[\"name\"] == \"Temp: RCRX IN \")\n  |> drop(columns: [\"host\", \"path\", \"source\", \"subscription\", \"location\",])\n"
    }
   ]
  },
  {
   "title": "$WLC Temp: RCRX OUT",
   "type": "bargauge",
   "description": "|  Sensor         | Threshold (Minor,Major,Critical,Shutdown) |\n| --------------- | ----------------------------------------- |\n|  RCRX OUT |     (62 ,67 ,72 ,80 )(Celsius)            |",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${Collector}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XE-environment-oper:environment-sensors/environment-sensor\")\n  |> filter(fn: (r) => r[\"source\"] == \"${WLC}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"current_reading\")\n  |> filter(fn: (r) => r[\"name\"] == \"Temp: RCRX OUT\")\n  |> drop(columns: [\"host\", \"path\", \"source\", \"subscription\", \"location\",])\n"
    }
   ]
  },
  {
   "title": "$WLC WNCD",
   "type": "gauge",
   "description": "If you are experiencing issues with data retrieval in this panel, please ensure that your Wireless LAN Controller (WLC) is running version 17.14 or higher. Additionally, verify that the Wireless Network Controller Daemon (WNCD) is actively processing data. You can check the WNCD usage by running the command show processes cpu platform sorted | i wncd on your WLC's command-line interface. If there is no load at the WNCD, the visualization may not display any data.",
   "gridPos": { "h": 9, "w": 7, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${Collector}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XE-platform-software-oper:system-resource\")\n  |> filter(fn: (r) => r[\"source\"] == \"${WLC}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"five-seconds\" or r[\"_field\"] == \"five-min\" or r[\"_field\"] == \"one-min\")\n  |> filter(fn: (r) => \n      r[\"name\"] == \"wncd_0\" or \n      r[\"name\"] == \"wncd_1\" or \n      r[\"name\"] == \"wncd_2\" or \n      r[\"name\"] == \"wncd_3\" or \n      r[\"name\"] == \"wncd_4\"\n  )\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)"
    }
   ]
  },
  {
   "title": "$WLC WNCD",
   "type": "timeseries",
   "description": "If you are experiencing issues with data retrieval in this panel, please ensure that your Wireless LAN Controller (WLC) is running version 17.14 or higher. Additionally, verify that the Wireless Network Controller Daemon (WNCD) is actively processing data. You can check the WNCD usage by running the command show processes cpu platform sorted | i wncd on your WLC's command-line interface. If there is no load at the WNCD, the visualization may not display any data.",
   "gridPos": { "h": 9, "w": 7, "x": 15, "y": 9 },
   "targets": [
    {
     "query": "from(bucket: \"${Collector}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XE-platform-software-oper:system-resource\")\n  |> filter(fn: (r) => r[\"source\"] == \"${WLC}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"five-seconds\" or r[\"_field\"] == \"five-min\" or r[\"_field\"] == \"one-min\")\n  |> filter(fn: (r) => \n      r[\"name\"] == \"wncd_0\" or \n      r[\"name\"] == \"wncd_1\" or \n      r[\"name\"] == \"wncd_2\" or \n      r[\"name\"] == \"wncd_3\" or \n      r[\"name\"] == \"wncd_4\"\n  )\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)"
    }
   ]
  },
  {
   "title": "Memory used $WLC",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "from(bucket: \"${Collector}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XE-memory-oper:memory-statistics/memory-statistic\")\n  |> filter(fn: (r) => r[\"_field\"] == \"used_memory\")\n  |> filter(fn: (r) => r[\"source\"] == \"${WLC}\")\n  |> filter(fn: (r) => r[\"name\"] == \"Processor\")\n  |> drop(columns: [\"host\", \"path\", \"source\", \"subscription\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n"
    }
   ]
  },
  {
   "title": "Memory free $WLC",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "from(bucket: \"${Collector}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XE-memory-oper:memory-statistics/memory-statistic\")\n  |> filter(fn: (r) => r[\"_field\"] == \"free_memory\")\n  |> filter(fn: (r) => r[\"source\"] == \"${WLC}\")\n  |> filter(fn: (r) => r[\"name\"] == \"Processor\")\n  |> drop(columns: [\"host\", \"path\", \"source\", \"subscription\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n"
    }
   ]
  },
  {
   "title": "Device Traffic $WLC",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "targets": [
    {
     "query": "from(bucket: \"${Collector}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XE-interfaces-oper:interfaces/interface\")\n  |> filter(fn: (r) => r[\"_field\"] == \"statistics/rx_kbps\" or r[\"_field\"] == \"statistics/tx_kbps\")\n  |> filter(fn: (r) => r[\"source\"] == \"${WLC}\")\n  |> filter(fn: (r) => r[\"_value\"] > 0)\n  |> drop(columns: [\"host\", \"path\", \"source\", \"subscription\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n"
    }
   ]
  },
  {
   "title": "$WLC HA Summary",
   "type": "table",
   "gridPos": { "h": 13, "w": 12, "x": 10, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsUS" } },
   "targets": [
    {
     "query": "from(bucket: \"${Collector}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XE-ha-oper:ha-oper-data/ha-infra\")\n  |> filter(fn: (r) => r[\"source\"] == \"${WLC}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> drop(columns: [\"leaf_mode\", \"_start\", \"_stop\", \"host\", \"path\", \"source\", \"subscription\", \"image_version\"])\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Packet Counter $WLC",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"${Collector}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XE-interfaces-oper:interfaces/interface\")\n  |> filter(fn: (r) => r[\"_field\"] == \"statistics/rx_pps\" or r[\"_field\"] == \"statistics/tx_pps\")\n  |> filter(fn: (r) => r[\"source\"] == \"${WLC}\")\n  |> filter(fn: (r) => r[\"_value\"] > 0)\n  |> drop(columns: [\"host\", \"path\", \"source\", \"subscription\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n"
    }
   ]
  }
 ]
}