{
 "title": "Demo 9800L",
 "tags": [
  "Demo",
  "Wireless"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "Collector", "query": "buckets()" },
   {
    "name": "WLC",
    "label": "WLC",
    "query": "from(bucket: \"${Collector}\")\n  |> range(start: v.timeRangeStart, stop: now())\n  |> keyValues(keyColumns: [\"source\"])\n  |> group(columns: [\"source\"])\n  |> keep(columns: [\"source\"])\n  |> distinct(column: \"source\")"
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime $WLC",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${Collector}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XE-device-hardware-oper:device-hardware-data/device-hardware\")\n  |> filter(fn: (r) => r[\"source\"] == \"${WLC}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"device_system_data/boot_time\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> drop(columns: [\"_time\", \"_start\", \"_stop\"]) // drop timestamp columns\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Version $WLC",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${Collector}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XE-native:native\")\n  |> filter(fn: (r) => r[\"_field\"] == \"version\")\n  |> drop(columns: [\"host\", \"path\", \"source\", \"subscription\"])\n\n\n"
    }
   ]
  },
  {
   "title": "ROMMON $WLC",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${Collector}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XE-device-hardware-oper:device-hardware-data/device-hardware\")\n  |> filter(fn: (r) => r[\"_field\"] == \"device_system_data/rommon_version\")\n  |> filter(fn: (r) => r[\"source\"] == \"${WLC}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> map(fn: (r) => ({ value: r[\"_value\"] }))\n  |> yield(name: \"last\")\n"
    }
   ]
  },
  {
   "title": "Last reload reason $WLC",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${Collector}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XE-device-hardware-oper:device-hardware-data/device-hardware\")\n  |> filter(fn: (r) => r[\"source\"] == \"${WLC}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"device_system_data/last_reboot_reason\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> drop(columns: [\"_time\", \"_start\", \"_stop\"]) // drop timestamp columns\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "$WLC CPU",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 7, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${Collector}\")\n  |> range(start: -15m)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XE-process-cpu-oper:cpu-usage/cpu-utilization\")\n  |> filter(fn: (r) => r[\"source\"] == \"${WLC}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"five_seconds\" or r[\"_field\"] == \"one_minute\" or r[\"_field\"] == \"five_minutes\") \n  |> drop(columns: [\"host\", \"path\", \"source\", \"subscription\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"${Collector}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XE-process-cpu-oper:cpu-usage/cpu-utilization\")\n  |> filter(fn: (r) => r[\"source\"] == \"${WLC}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"five_seconds\" or r[\"_field\"] == \"one_minute\" or r[\"_field\"] == \"five_minutes\") \n  |> drop(columns: [\"host\", \"path\", \"source\", \"subscription\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n"
    }
   ]
  },
  {
   "title": "$WLC Temperature",
   "type": "bargauge",
   "description": "|  Sensor         | Threshold (Minor,Major,Critical,Shutdown) |\n| --------------- | ----------------------------------------- |\n|  Temp: BRDTEMP1 |     (54 ,57 ,60 ,61 )(Celsius)            |\n|  Temp: BRDTEMP2 |     (58 ,61 ,64 ,65 )(Celsius)            |\n|  Temp: CPU Die  |     (94 ,99 ,104,105)(Celsius)            |",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${Collector}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XE-environment-oper:environment-sensors/environment-sensor\")\n  |> filter(fn: (r) => r[\"source\"] == \"${WLC}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"current_reading\")\n  |> drop(columns: [\"host\", \"path\", \"source\", \"subscription\", \"location\",])\n"
    }
   ]
  },
  {
   "title": "Memory used $WLC",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "from(bucket: \"${Collector}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XE-memory-oper:memory-statistics/memory-statistic\")\n  |> filter(fn: (r) => r[\"_field\"] == \"used_memory\")\n  |> filter(fn: (r) => r[\"source\"] == \"${WLC}\")\n  |> filter(fn: (r) => r[\"name\"] == \"Processor\")\n  |> drop(columns: [\"host\", \"path\", \"source\", \"subscription\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n"
    }
   ]
  },
  {
   "title": "Memory free $WLC",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "from(bucket: \"${Collector}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XE-memory-oper:memory-statistics/memory-statistic\")\n  |> filter(fn: (r) => r[\"_field\"] == \"free_memory\")\n  |> filter(fn: (r) => r[\"source\"] == \"${WLC}\")\n  |> filter(fn: (r) => r[\"name\"] == \"Processor\")\n  |> drop(columns: [\"host\", \"path\", \"source\", \"subscription\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n"
    }
   ]
  },
  {
   "title": "$WLC Access Points",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 10, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${Collector}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XE-wireless-access-point-oper:access-point-oper-data/ap-name-mac-map\")\n  |> filter(fn: (r) => r[\"source\"] == \"${WLC}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"wtp_mac\")\n  |> group()\n  |> distinct(column: \"_value\")\n  |> count()"
    }
   ]
  },
  {
   "title": "$WLC Top WLANs",
   "type": "table",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "query": "from(bucket: \"${Collector}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r[\"_measurement\"] == \"Cisco-IOS-XE-wireless-ap-global-oper:ap-global-oper-data/wlan-client-stats\" and\n    r[\"source\"] == \"${WLC}\" and\n    (r[\"_field\"] == \"wlan_profile_name\" or r[\"_field\"] == \"data_usage\")\n  )\n  |> pivot(\n    rowKey:[\"_time\"],\n    columnKey: [\"_field\"],\n    valueColumn: \"_value\"\n  )\n  |> filter(fn: (r) => r[\"wlan_profile_name\"] != \"\" and r[\"data_usage\"] != 0)\n  |> keep(columns: [\"wlan_profile_name\", \"data_usage\"])"
    }
   ]
  },
  {
   "title": "$WLC Clients per SSID",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 10, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${Collector}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XE-wireless-wlan-global-oper:wlan-global-oper-data/wlan-info\")\n  |> filter(fn: (r) => r[\"source\"] == \"${WLC}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"curr_clients_count\")\n  |> drop(columns: [\"host\", \"path\", \"source\", \"subscription\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Device Traffic $WLC",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "targets": [
    {
     "query": "from(bucket: \"${Collector}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XE-interfaces-oper:interfaces/interface\")\n  |> filter(fn: (r) => r[\"_field\"] == \"statistics/rx_kbps\" or r[\"_field\"] == \"statistics/tx_kbps\")\n  |> filter(fn: (r) => r[\"source\"] == \"${WLC}\")\n  |> filter(fn: (r) => r[\"_value\"] > 0)\n  |> drop(columns: [\"host\", \"path\", \"source\", \"subscription\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n"
    }
   ]
  },
  {
   "title": "$WLC HA Summary",
   "type": "table",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsUS" } },
   "targets": [
    {
     "query": "from(bucket: \"${Collector}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XE-ha-oper:ha-oper-data/ha-infra\")\n  |> filter(fn: (r) => r[\"source\"] == \"${WLC}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> drop(columns: [\"leaf_mode\", \"_start\", \"_stop\", \"host\", \"path\", \"source\", \"subscription\", \"image_version\"])\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Packet Counter $WLC",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"${Collector}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cisco-IOS-XE-interfaces-oper:interfaces/interface\")\n  |> filter(fn: (r) => r[\"_field\"] == \"statistics/rx_pps\" or r[\"_field\"] == \"statistics/tx_pps\")\n  |> filter(fn: (r) => r[\"source\"] == \"${WLC}\")\n  |> filter(fn: (r) => r[\"_value\"] > 0)\n  |> drop(columns: [\"host\", \"path\", \"source\", \"subscription\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n"
    }
   ]
  }
 ]
}